### ISSUE TITLE
[Bug] Crash

### ISSUE THREAD

**Issue by Anonimouze** [Nekiplay/MeteorPlus#104]
### Describe the bug

Game crashes
[2024-02-23-1.log.gz](https://github.com/Nekiplay/MeteorPlus/files/14382211/2024-02-23-1.log.gz)

### Steps to reproduce

```bash
.
```

### Meteor Plus Version

Latest Release 

### Minecraft Version

0.5.6-2024

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Nekiplay** [comment]
Have you tried logging in without ThunderHack?

**Comment by Nekiplay** [comment]
Try last commit
