### ISSUE TITLE
[Bug] multi tasks module is blank

### ISSUE THREAD

**Issue by GavinGoGaming** [Nekiplay/MeteorPlus#107]
### Describe the bug

dunno why it exists

### Steps to reproduce

```bash
- open game
- check modules
- multitasks exists (but code file for it is legit blank besides constructer)
```

### Meteor Plus Version

1.0.5

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Nekiplay** [comment]
Module need onfy for Enabling - Disabling, its using in Mixin
https://github.com/Nekiplay/MeteorPlus/blob/main/src/main/java/nekiplay/meteorplus/mixin/minecraft/MinecraftClientMixin.java
