### ISSUE TITLE
[Bug] Cant make long prompt for gpt command

### ISSUE THREAD

**Issue by fungoza** [Nekiplay/MeteorPlus#111]
### Describe the bug

![image](https://github.com/Nekiplay/MeteorPlus/assets/68079109/1d7d3d61-5aa3-483c-ba99-6d1d445132fb)
only accepts first word

### Steps to reproduce

```bash
chatgpt nagaai
.gpt one two three
```

### Meteor Plus Version

1.0.7

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Nekiplay** [comment]
use .gpt "text promt"
