### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by CoolNateJr** [Nekiplay/MeteorPlus#114]
### Describe the bug

it says its a trojan

### Steps to reproduce

```bash
downloading it
```

### Meteor Plus Version

1.0.7

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Nekiplay** [comment]
> ### Describe the bug
> it says its a trojan

Okay
