### ISSUE TITLE
[Bug] The MeteorPlus category in Clickgui does not show up in the latest MeteorPlus update

### ISSUE THREAD

**Issue by Ancnymous** [Nekiplay/MeteorPlus#121]
### Describe the bug

Wasn't a issue on the older builds.

### Steps to reproduce

```bash
Launch the game with latest meteor plus github release and latest meteor dev build from github and the MeteorPlus category won't show up in Clickgui so you have to manually search everything up.
```

### Meteor Plus Version

Latest Github Release 

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Nekiplay** [comment]
Remive meteorclient folder
