### ISSUE TITLE
[Bug] client crashing at lunch 1.20.4

### ISSUE THREAD

**Issue by Hiradpi** [Nekiplay/MeteorPlus#122]
### Describe the bug

the bug is from meteor-plus I tried removing baritone adding baritone API ,removing every single mod and trying without them exept sodium and meteor ofc , works fine in the version 1.20.1 

[crash-2024-05-03_18.50.20-client.txt](https://github.com/Nekiplay/MeteorPlus/files/15202162/crash-2024-05-03_18.50.20-client.txt)

### Steps to reproduce

```bash
just trying to launch
```

### Meteor Plus Version

I tried with 1.0.7 - 1.0.8.8

### Minecraft Version

minecraft 1.20.4 , fabric 0.15.11 , fabric-api-0.97.0 , meteor-client-0.5.6-2066

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Hiradpi** [comment]
why can't i just downgrade ?
is the build version i have only build for 1.20.4 ?

**Comment by Big-Iron-Cheems** [comment]
If you want to downgrade, you may build the source at [this](https://github.com/MeteorDevelopment/meteor-client/tree/2517862a2b88f514c5302ccabcc50fbcc33e4fb5) commit, before our change was applied.

**Comment by Hiradpi** [comment]
when is the meteor plus is going to fix and make it self compatible with the new keybind system ? and am I the only one that has this problem ?
building meteor my self didn't help faced me with other kinds of errors I know this is a free project but come on it has been almost 3 weeks and meteor plus is too popular and useful to be ignored like this <3

**Comment by MCdiax** [comment]
it's fixed already
