### ISSUE TITLE
MeteorPlus will crash Mod Menu(the mod)[Bug] 

### ISSUE THREAD

**Issue by E0x72-21** [Nekiplay/MeteorPlus#124]
### Describe the bug

crash report: https://mclo.gs/Yf3BPhC

### Steps to reproduce

```bash
1. run the game with MeteorPlus, Meteor and Mod Menu
2. scroll down the Mod Menu's menu
```

### Meteor Plus Version

1.0.8.8

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by E0x72-21** [comment]
Supplement: This bug will not appear in meteorplus1.0.8.7

**Comment by Quanvm0501** [comment]
Lol I tried and the meteor still crash while the mod menu it's disabled

**Comment by E0x72-21** [comment]
Supplement: meteorplus1.0.9.0 **still** has this bug

**Comment by Nekiplay** [comment]
Fixed?
I don't have any problems.
