### ISSUE TITLE
Crash with Meteor0.5.6 bulid≥2066[Bug] 

### ISSUE THREAD

**Issue by E0x72-21** [Nekiplay/MeteorPlus#125]
### Describe the bug

crash report: https://mclo.gs/5D5EdnL

### Steps to reproduce

```bash
run the game with meteor0.5.6 release and meteorplus1.0.8.8
```

### Meteor Plus Version

1.0.8.8

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by E0x72-21** [comment]
https://github.com/MeteorDevelopment/meteor-client/issues/4569#issuecomment-2096168585

**Comment by Nekiplay** [comment]
I use Java 21 from Zulu for the same reason that in it all better, meteor client at least became playable fucking half Russian
![image](https://github.com/Nekiplay/MeteorPlus/assets/35975332/44de62e3-a862-41e1-8634-219244871f79)
![image](https://github.com/Nekiplay/MeteorPlus/assets/35975332/bf7c6765-e1dc-4c0a-9bde-3bfb4477f71a)

**Comment by Nekiplay** [comment]
Fixed
