### ISSUE TITLE
XRay BruteForce is not working properly.

### ISSUE THREAD

**Issue by 2x9Mon** [Nekiplay/MeteorPlus#13]
It seems that Xray Bruteforce scans the wrong blocks w/ default settings on anti-xray servers. Any tips?

**Comment by Nekiplay** [comment]
XRay BruteForce does not work on new server versions

**Comment by 2x9Mon** [comment]
I see, so is this an old paste of AAX for 1.16?

**Comment by Nekiplay** [comment]
1.16.5 and below should work
