### ISSUE TITLE
Printer Mode

### ISSUE THREAD

**Issue by TheSrBig** [Nekiplay/MeteorPlus#134]
### Describe the bug

when using printer, in 2b2t, it shows the blocks but apparently there is a bug that the first block is not shown, but the second one is.
![image](https://github.com/Nekiplay/MeteorPlus/assets/89810837/87190376-1510-4e42-9ae5-3d4583c5f6f3)

### Steps to reproduce

```bash
enable printer in 2b
```

### Meteor Plus Version

meteor-plus-1.20.4_1.0.9.0

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Nekiplay** [comment]
Printer is not intended for servers with anti-readers
