### ISSUE TITLE
[Bug] Killaura better 

### ISSUE THREAD

**Issue by ZingMCPC** [Nekiplay/MeteorPlus#136]
### Describe the bug

When I opened Killaura better it crash immediately

### Steps to reproduce

```bash
Turn on killaura better
```

### Meteor Plus Version

meteor-plus-1.19.4-release-2-for-dev-build-0.5.3

### Minecraft Version

1.19.4

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [x] This is a valid bug.

**Comment by Nekiplay** [comment]
1.19.4 not support
