### ISSUE TITLE
update to 1.20.6 plz [Suggestion] 

### ISSUE THREAD

**Issue by lyy2182** [Nekiplay/MeteorPlus#138]
### Description

Update MeteorPlus to 1.20.6 plz

### Before submitting a suggestion

- [X] This feature doesn't already exist.

- [X] This wasn't already suggested.

**Comment by RockingCha1r** [comment]
true

**Comment by MCdiax** [comment]
+1

**Comment by minecraftchest1** [comment]
https://github.com/Nekiplay/MeteorPlus/issues/123
