### ISSUE TITLE
[Bug] Added MeteorPlus crashes game

### ISSUE THREAD

**Issue by Artemyu45** [Nekiplay/MeteorPlus#142]
### Describe the bug

https://paste.ee/p/G8CEX

### Steps to reproduce

```bash
I played with Meteor then I was want to add MeteorPlus and game started but then immediatly crashed
I tried different java versions and MeteorPlus version
Didn't starts anyway
I have fabric api
```

### Meteor Plus Version

i tried 1.0.8.8 and 1.0.9.0 - both not working

### Minecraft Version

1.20.4 Meteor - 0.5.6-2065

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Nekiplay** [comment]
You have meteor client in mods folder?

**Comment by MCdiax** [comment]
I have the same problem

**Comment by Nekiplay** [comment]
> MCdiax

send log

**Comment by Artemyu45** [comment]
Yes i am

ср, 4 сент. 2024 г., 03:37 Roman Danilov ***@***.***>:
