### ISSUE TITLE
[Suggestion] 1.21

### ISSUE THREAD

**Issue by IAmStive222** [Nekiplay/MeteorPlus#147]
### Description

Please add support for version 1.21

### Before submitting a suggestion

- [X] This feature doesn't already exist.

- [X] This wasn't already suggested.

**Comment by Nekiplay** [comment]
[mods.zip](https://github.com/user-attachments/files/16631780/mods.zip)
1.21.1

**Comment by Crappy-Productions** [comment]
1.21 ≠ 1.21.1
