### ISSUE TITLE
[Bug] "multiTasks" is null

### ISSUE THREAD

**Issue by NotAUser-1059** [Nekiplay/MeteorPlus#148]
### Describe the bug

Crashed as soon as I joined a server
Log: https://pastebin.com/raw/QzR9fDRk

### Steps to reproduce

```bash
Join a server
```

### Meteor Plus Version

1.0.9.0

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Nekiplay** [comment]
https://github.com/Nekiplay/MeteorPlus/blob/main/src/main/java/nekiplay/meteorplus/mixin/minecraft/MinecraftClientMixin.java

**Comment by Nekiplay** [comment]
Fix
