### ISSUE TITLE
Ideas for new modules/Bugs

### ISSUE THREAD

**Issue by Vlad-ang** [Nekiplay/MeteorPlus#15]

**Comment by Vlad-ang** [comment]
Auto Login

Better NameTags(что нибудь новое в неймтегсы/улучшенная кастомизация)

LangFix(Чтобы метеор видел русский язык ибо русский он не видит)

BetterChat Plus(Чтобы чат сохранялся после перезахода на сервер к примеру; добавить собственное кд на отправление сообщения серверу)

**Comment by Vlad-ang** [comment]
Исправить баг с AutoSell, если нужно выставлять в определенном количестве,( в хотбаре сразу разложенно в нужном количестве), модуль пишет автосел, но предмет не продается(к примеру лоты для продажи на данный момент заняты) тогда предметы стакаются в один слот.

**Comment by Vlad-ang** [comment]
SafeMine добавить защиту от гравия, к примеру чтобы игрок не мог сломать плотный блок над  собой, над которым находится гравий/песок и прочие блоки с гравитацией

**Comment by Nekiplay** [comment]
> SafeMine добавить защиту от гравия, к примеру чтобы игрок не мог сломать плотный блок над собой, над которым находится гравий/песок и прочие блоки с гравитацией

Позже может появиться

**Comment by Nekiplay** [comment]
> Auto Login
> 
> Better NameTags(что нибудь новое в неймтегсы/улучшенная кастомизация)
> 
> LangFix(Чтобы метеор видел русский язык ибо русский он не видит)
> 
> BetterChat Plus(Чтобы чат сохранялся после перезахода на сервер к примеру; добавить собственное кд на отправление сообщения серверу)

LagFix не возможен
BetterChat Plus возможен но он не нужен так как PolyMC сохраняет все логи чаиа
