### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Vlad-ang** [Nekiplay/MeteorPlus#17]

**Comment by Vlad-ang** [comment]
Auto Repair chat feedback 
Auto sell Chat feedback 
Если его выключить Chat Feedback то всё равно он будет писать в чат

**Comment by Vlad-ang** [comment]
Auto sell
Бывает не выставляет предметы, как бы в инве ресы для продажи положены, он включен (не выключается), а просто нифига не пишет. Без понятия с чем связано

**Comment by Vlad-ang** [comment]
Auto sell 
если в цену за 1 предмет написать случайно букву, а не цифру то при попытке выставить предмет на аук майн крашит

**Comment by Vlad-ang** [comment]
Auto Accept  
Если выбрать чтобы принимало тп от всех — крашит майн

**Comment by Nekiplay** [comment]
> Auto Repair chat feedback Auto sell Chat feedback Если его выключить Chat Feedback то всё равно он будет писать в чат

Its not a bug
