### ISSUE TITLE
Ideas for new modules

### ISSUE THREAD

**Issue by Vlad-ang** [Nekiplay/MeteorPlus#18]
Eagle из liquidebounce(автоматическое строительство с отпусканием шифта)

Auto Brewer +, улучшенное автобафо варение, дефолтное иногда глючит и делает заурядное зелье

Auto Villager roller(такой аддон для метеора уже есть, но он на 1.19, если не сложно можешь скомпилировать на 1.18.2)

Спиды для элитры(чтобы быстрее летать именно, а не просто ходить)

**Comment by Vlad-ang** [comment]
Auto Leave 
Добавить возможность добавлять ещё пару команд чтобы писало для лива, а не только 1
К примеру /spawn, и через секунды 3 /hub

**Comment by Vlad-ang** [comment]
Better Chat+ сохранять историю после выхода с сервера, секунды к timestamps
PolyMc только с лицухи запускается, пиратам надо бесплатное что-то)

**Comment by Nekiplay** [comment]
> Better Chat+ сохранять историю после выхода с сервера, секунды к timestamps PolyMc только с лицухи запускается, пиратам надо бесплатное что-то)

Minecraft сохраняет логи в папку logs в том числе и чата

**Comment by Vlad-ang** [comment]
Я знаю что такое логи, но я имею ввиду сохранение чата в визуалке майна чат, а не файл .logs

**Comment by Nekiplay** [comment]
Pls write on english language for reviev other players

**Comment by Nekiplay** [comment]
1.18.2 not support
