### ISSUE TITLE
PLS FIX so I have ka better. (Or make old versions avable)

### ISSUE THREAD

**Issue by arandommenno** [Nekiplay/MeteorPlus#21]
When I start the client with the the mods listed in the crash report the game crashes.
And I am no crash report person but I have not enough crashes and it says that meteorplus is the problem.

[crash-2022-10-31_15.22.48-client.txt](https://github.com/Nekiplay/MeteorPlus/files/9901932/crash-2022-10-31_15.22.48-client.txt)

**Comment by Nekiplay** [comment]
fixed
