### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by LiamRay10** [Nekiplay/MeteorPlus#22]
it no work

**Comment by I-Got-You-Dead** [comment]
Cry about it

**Comment by I-Got-You-Dead** [comment]
And close the issue

**Comment by qeqeqeplayer533** [comment]
try smoothboot mod

**Comment by I-Got-You-Dead** [comment]
What is that gonna do

**Comment by I-Got-You-Dead** [comment]
All it does is change how many cpu threads are used

**Comment by I-Got-You-Dead** [comment]
Also stop replying to dead issues from months ago
