### ISSUE TITLE
XRay Bruteforce malfunctioning

### ISSUE THREAD

**Issue by Lawerencium** [Nekiplay/MeteorPlus#25]
The XRay Bruteforce module doesnt do what it says it should. 

For as far as i know it should bypass anti-xray right? Well, for everything i tried it also shows all the diamond_ores that the anti-xray plugin sends from the server to the client, so it just shows thousands of ESP blocks because it detects the blocks from the plugin too.

Please update it so it actually checks if its a real diamond_ore if that is possible. Would be nice as this is one of the only modules that promises to bypass anti-xray. Greetings!

**Comment by Lawerencium** [comment]
![image](https://user-images.githubusercontent.com/44242146/210391706-e05e0fc1-fc5d-4bb4-9f06-b8347bf3f73d.png)

**Comment by Nekiplay** [comment]
Use max 3 blocks range
