### ISSUE TITLE
мегапаник

### ISSUE THREAD

**Issue by erxson** [Nekiplay/MeteorPlus#30]
Если не лень, не мог бы ты сделать какой-то мегапаник модуль/команду, которая сделает папку с конфигами скрытой или даже системно скрытой и сотрет все упоминания метеора в логах? или шотатипатаво

**Comment by Nekiplay** [comment]
> Если не лень, не мог бы ты сделать какой-то мегапаник модуль/команду, которая сделает папку с конфигами скрытой или даже системно скрытой и сотрет все упоминания метеора в логах? или шотатипатаво

У меня в планах сделать Fork метеор клиента для легитеров

**Comment by erxson** [comment]
> > Если не лень, не мог бы ты сделать какой-то мегапаник модуль/команду, которая сделает папку с конфигами скрытой или даже системно скрытой и сотрет все упоминания метеора в логах? или шотатипатаво
> 
> У меня в планах сделать Fork метеор клиента для легитеров

Целую твои мысли

**Comment by Nekiplay** [comment]
You don't have to
