### ISSUE TITLE
Add Ignore Friends option to Triggerbot

### ISSUE THREAD

**Issue by abobainc** [Nekiplay/MeteorPlus#31]
Add Ignore Friends option to Triggerbot

**Comment by abobainc** [comment]
It also attacks all entities no matter if I have them selected or not

**Comment by I-Got-You-Dead2** [comment]
Cope

**Comment by I-Got-You-Dead2** [comment]
You do know trigger bot is built into meteor roght

**Comment by Nekiplay** [comment]
Why do you need this function? You can just not add opponents to your friends
