### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by Helemp** [Nekiplay/MeteorPlus#32]
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: meteordevelopment/meteorclient/systems/modules/render/blockesp/ESPBlockData
![Minecraft_Launcher_2_17_2023_4_33_17_PM](https://user-images.githubusercontent.com/120613527/223296864-d7b8b4ae-6ce5-44a9-95fc-e0d33c5c25dc.png)

**Comment by I-Got-You-Dead2** [comment]
1: send a log
2: known issue

**Comment by FeloFn** [comment]
happen to me to

**Comment by Appolon24800** [comment]
Yeh the new meteor update break the addon :/

**Comment by Nekiplay** [comment]
fixed
