### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Renartared** [Nekiplay/MeteorPlus#37]
<img width="779" alt="Screenshot 2023-04-16 at 14 26 57" src="https://user-images.githubusercontent.com/119152392/232276785-eff51900-cdf3-464e-9a8b-bc7ff609aa04.png">

**Comment by Nekiplay** [comment]
> <img alt="Screenshot 2023-04-16 at 14 26 57" width="779" src="https://user-images.githubusercontent.com/119152392/232276785-eff51900-cdf3-464e-9a8b-bc7ff609aa04.png">

Meteor Plus vesion? Meteor Client version?

**Comment by Renartared** [comment]
Newest meteor client version and newest meteor plus version

**Comment by Nekiplay** [comment]
> Newest meteor client version and newest meteor plus version

Say version minecraft and version meteor client or meteor client dev build number
Send log

**Comment by Nekiplay** [comment]
> Newest meteor client version and newest meteor plus version

If I'm asking for the version you need to write which version, if Dev Build, then specify which one, the problem should have been solved
