### ISSUE TITLE
Better Notebot module

### ISSUE THREAD

**Issue by Darknicomars** [Nekiplay/MeteorPlus#40]
All in the name, a better notebot module with a printer in it to setup the noteblocks (file of the schematic if you want)
[Noteblocks for Notebot.zip](https://github.com/Nekiplay/MeteorPlus/files/11404639/Noteblocks.for.Notebot.zip)

And if possible a setting to upload mp3 songs and convert them in the minecraft format

**Comment by I-Got-You-Dead2** [comment]
No

**Comment by I-Got-You-Dead2** [comment]
Cope

**Comment by Nekiplay** [comment]
The addon is designed to bypass anti-cheats
