### ISSUE TITLE
AutoLeave command

### ISSUE THREAD

**Issue by BanAvade** [Nekiplay/MeteorPlus#41]
Не отправляет команду в чат а создаёт в чате какой то messagebox с командой белым цветом.
![image](https://github.com/Nekiplay/MeteorPlus/assets/132976973/41a17a0b-1958-410b-b15a-ff28ee1f9038)

**Comment by bluepanee** [comment]
Это происходит из-за того, что сообщение отправляется не на сервер, а добавляется в историю чата на клиентсайде. Похожие проблемы есть и в других модулях, в которых есть возможность отправлять команды.
В теории, это можно починить  простой заменой `mc.player.sendMessage(...)` на `mc.getNetworkHandler().sendChatCommand(...)`. 
Займусь этим, когда наконец-то примут [пулл реквест на апдейт до 1.20](#44).

**Comment by Nekiplay** [comment]
Fixed in 1.20.1?

**Comment by bluepanee** [comment]
> Fixed in 1.20.1?

No, it's not. 

`mc.player.sendMessage( ... );` should be replaced with `ChatUtils.sendPlayerMsg( ... );` since `mc.player.sendMessage` adds the message to your hud.

This error also appears in the AutoSell, AutoAccept, AutoRepair and AutoMend modules.
