### ISSUE TITLE
Update to 1.20

### ISSUE THREAD

**Issue by Alex81341** [Nekiplay/MeteorPlus#43]
meteor client updated to 1.20

**Comment by JACKKY04** [comment]
Bump

**Comment by JACKKY04** [comment]
1.20.1 Is now out, Is there any update on whether this mod will be getting support?

**Comment by ROM0071235** [comment]
will MeteorPlus update to 1.20.1 or at least 1.20?

**Comment by JACKKY04** [comment]
> will MeteorPlus update to 1.20.1 or at least 1.20?

Who knows XD

**Comment by bluepanee** [comment]
> will MeteorPlus update to 1.20.1 or at least 1.20?

Yep. #44
