### ISSUE TITLE
Meteor Plus fork.

### ISSUE THREAD

**Issue by bluepanee** [Nekiplay/MeteorPlus#46]
Could you please list me as a co-author next time you copy code from my [fork](https://github.com/bluepanee/meteor-plus-plus)? I hope for your understanding.

**Comment by Nekiplay** [comment]
I mentioned your Fork in the comit addendum and if you have great ideas for Hidden modules why not put them in the main repository?
https://github.com/Nekiplay/MeteorPlus/commit/eb6f0ce497d2be88754f64c405a49aab5004eb20

**Comment by bluepanee** [comment]
My bad. Didn't noticed it. 

> if you have great ideas for Hidden modules why not put them in the main repository?

I thought the addon was abandoned due to lack of commits, so I created a fork for myself with some fixes and tweaks.
