### ISSUE TITLE
Old Animation 1.7-1.8

### ISSUE THREAD

**Issue by NCPUser** [Nekiplay/MeteorPlus#61]
Мне нравица эти анимации добавьте на 1.20.1 это будет ахуенно!

**Comment by Nekiplay** [comment]
В Hand View уже есть

**Comment by NCPUser** [comment]
> В Hand View уже есть

Не я про блок из 1.7-1.8 он топ

**Comment by Nekiplay** [comment]
Create in Meteor Client github enhancement
