### ISSUE TITLE
Game crashing.

### ISSUE THREAD

**Issue by KianKrause** [Nekiplay/MeteorPlus#69]
Hello everytime i activate killaura better and its hitting enitities my game is instantly crashing.
pls help.

**Comment by Nekiplay** [comment]
send crash log

**Comment by KianKrause** [comment]
[crash-2023-09-10_21.42.53-client.txt](https://github.com/Nekiplay/MeteorPlus/files/12570088/crash-2023-09-10_21.42.53-client.txt)

**Comment by Nekiplay** [comment]
Meteor Plus no longer suport 1.19.4, use 1.20.1
