### ISSUE TITLE
[Bug] Why can't you nocom scan in 1.17+? (X-ray bruteforce)

### ISSUE THREAD

**Issue by Inn3rstellar** [Nekiplay/MeteorPlus#71]
### Describe the bug

Basically, a while ago, there was a bug on this saying nocom doesn't work and it scans the wrong blocks. Then your answer was "It doesn't work on newer server versions." Would you please explain why?

### Steps to reproduce

```bash
Use xray bruteforce
```

### Meteor Plus Version

idk

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Nekiplay** [comment]
Because of a patch in the server core that does not allow you to get information about a block that is further than 5 blocks from the player
