### ISSUE TITLE
[Bug] Game Crashing on startup

### ISSUE THREAD

**Issue by ModxVoldHunter** [Nekiplay/MeteorPlus#72]
### Describe the bug

i have mods and a few others, i installed essentials and meteor plus started to look for xaero maps classes and then it crashes

### Steps to reproduce

```bash
Download the modpack there is meteor, meteor plus, tokyo addon, meteorist addon, and other plus optimization mods and then hit start. im currently using prism launcher.

it crashed when starting up and here is the link:https://drive.google.com/file/d/14W4CIafbT7Lk7PX7ba8TWXFhVFZLAZEl/view?usp=sharing

and idk why it crashes when i start it up, i get this crash log. https://mclo.gs/C7nKQTi
```

### Meteor Plus Version

1.0.4

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by alcgabriel** [comment]
its same for me, but i using the official launcher, with clientcommands, meteor client 5.5, meteor plus 1.0.4, meteor crash addon, sodium fabric, tried to use only the meteor client and meteor plus with fabric, and crash 
![image](https://github.com/Nekiplay/MeteorPlus/assets/85556196/d4431ff3-f606-4340-9abb-b232fc6b7ae4)

**Comment by ModxVoldHunter** [comment]
yeah its strange, at first i thought it was a meteor problem, but don't know.

**Comment by Nekiplay** [comment]
Solved?

**Comment by alcgabriel** [comment]
no

**Comment by Nekiplay** [comment]
> no

Send you'r mods for test

**Comment by Nekiplay** [comment]
> > no
> 
> Send you'r mods for test

And try Meteor Client version from Guilded

**Comment by alcgabriel** [comment]
> > no
> 
> Send you'r mods for test

![image](https://github.com/Nekiplay/MeteorPlus/assets/85556196/ded4184b-a8e8-4ca6-8d64-caca4f0dfb4d)

**Comment by Nekiplay** [comment]
Try on Meteor Client 1944

**Comment by alcgabriel** [comment]
idk where i can download this ver

**Comment by Nekiplay** [comment]
> idk where i can download this ver

or for last build in https://github.com/Nekiplay/MeteorPlus/blob/main/libs/

![image](https://github.com/Nekiplay/MeteorPlus/assets/35975332/97d14d3b-a605-4714-b329-fb4e9e73329e)

**Comment by alcgabriel** [comment]
@ModxVoldHunter need's to download this specific [ver](https://www.guilded.gg/Monolith-Development/groups/DbjNmZ7D/channels/27cc979c-a4cf-4002-8746-693afcc991bd/docs/395526)

**Comment by Nekiplay** [comment]
Its work https://github.com/Nekiplay/MeteorPlus/releases/tag/1.20.2

**Comment by ModxVoldHunter** [comment]
ill test it with the version provided later.

**Comment by ModxVoldHunter** [comment]
Game is working with Libs provided. Closing.
No crashes were reported. thank you.
