### ISSUE TITLE
Bring Back the Best feature, "Container cleaner"

### ISSUE THREAD

**Issue by Eragon1250** [Nekiplay/MeteorPlus#73]
### Description

ContainerCleaner was removed, because Meteor got a replacement in InventoryTweaks, but the replacement is harder to configure and also you cant turn the dropping of items on and of with a single button anymore, because you can only activate and deactivate InventoryTweaks as a whole, before it was possible for me to activate the containercleaner with a single butonpress(the good old times).

so plsbring back the ContainerCleaner or make a new hotkey function in InventoryTweaks

### Before submitting a suggestion

- [X] This feature doesn't already exist.

- [X] This wasn't already suggested.

**Comment by Nekiplay** [comment]
> ### Description
> ContainerCleaner was removed, because Meteor got a replacement in InventoryTweaks, but the replacement is harder to configure and also you cant turn the dropping of items on and of with a single button anymore, because you can only activate and deactivate InventoryTweaks as a whole, before it was possible for me to activate the containercleaner with a single butonpress(the good old times).
> 
> so plsbring back the ContainerCleaner or make a new hotkey function in InventoryTweaks
> 
> ### Before submitting a suggestion
> * [x]  This feature doesn't already exist.
> * [x]  This wasn't already suggested.

Use build from Guilded this build has Meteor Plus and Meteor Client, In the next update, we'll update

**Comment by Nekiplay** [comment]
> ContainerCleaner was removed, because Meteor got a replacement in InventoryTweaks, but the replacement is harder to configure and also you cant turn the dropping of items on and of with a single button anymore, because you can only activate and deactivate InventoryTweaks as a whole, before it was possible for me to activate the containercleaner with a single butonpress(the good old times).

Use Auto Drop module
