### ISSUE TITLE
[Bug] Game crashes on startup 

### ISSUE THREAD

**Issue by GODLIKE-ro** [Nekiplay/MeteorPlus#74]
### Describe the bug

The game crashes on startup with MeteorPlus enabled but works fine without MeteorPlus. 

### Steps to reproduce

```bash
-add meteor client and meteorplus
-launch minecraft 1.20.2(fabric)
```

### Meteor Plus Version

1.0.4

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Nekiplay** [comment]
duplacate of #72
