### ISSUE TITLE
[Bug] Meteor Plus does not work without baritone

### ISSUE THREAD

**Issue by ghost** [Nekiplay/MeteorPlus#75]
### Describe the bug
Starting Meteor Plus without Baritone installed will crash, despite not being explicitly listed as a dependency in `fabric.mod.json`

[latest.log](https://github.com/Nekiplay/MeteorPlus/files/13304805/latest.log)

### Steps to reproduce
1. Start Minecraft with Baritone, Meteor Client, and Meteor Plus installed.
2. Notice how it starts up and runs perfectly fine
3. Start Minecraft again, but this time with only Meteor CLient and Meteor Plus installed.
4. The game crashes

### Meteor Plus Version
1.0.4

### Minecraft Version
1.20.2

### Operating System
Linux

### Before submitting a bug report
- [X] This bug wasn't already reported.
- [X] This is a valid bug.

**Comment by Nekiplay** [comment]
duplacate of #72
Use last version meteor plus and baritone-api from Guilded or [from libs](https://github.com/Nekiplay/MeteorPlus/blob/main/libs/baritone-unoptimized-fabric-1.20.2-SNAPSHOT.jar)

**Comment by Nekiplay** [comment]
The problem is that meteor client 0.5.5 does not include baritone api add it to the mods folder
