### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by TherealONE12** [Nekiplay/MeteorPlus#77]
### Describe the bug

Meteor plus crashes with these mods:
![image](https://github.com/Nekiplay/MeteorPlus/assets/144170391/433b095d-2f53-4444-85c5-d44c78c34e18)
PLS help.

### Steps to reproduce

```bash
Just make an 1.20.2 fabric configuration, Put in all mods and you got it.
```

### Meteor Plus Version

Meteor-Plus-1.0.4

### Minecraft Version

1.20.2

### Operating System

Windows 11

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Nekiplay** [comment]
Log?

**Comment by Nekiplay** [comment]
Need baritone-api not baritone-standalone

**Comment by TherealONE12** [comment]
U now where i can get it for 1.20.2

**Comment by TherealONE12** [comment]
> Need baritone-api not baritone-standalone

U now where to get it for 1.20.2? The official Baratone Github doesnt have 1.20.2 support

**Comment by Nekiplay** [comment]
> > Need baritone-api not baritone-standalone
> 
> U now where to get it for 1.20.2? The official Baratone Github doesnt have 1.20.2 support

https://github.com/cabaletta/baritone/tree/1.20.2

**Comment by Nekiplay** [comment]
https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=event%3Apush+is%3Asuccess+branch%3A1.20.2

**Comment by TherealONE12** [comment]
THX all worked :)))))))))))
