### ISSUE TITLE
Killaura

### ISSUE THREAD

**Issue by Lor1co** [Nekiplay/MeteorPlus#8]
rotations work but client-sided. From my alt account my head standing still

**Comment by Nekiplay** [comment]
Rotation mode?

**Comment by Lor1co** [comment]
look at this https://www.youtube.com/watch?v=SkaljF6DMwY

**Comment by Nekiplay** [comment]
What mods do you use? and is there such a problem with the usual KillAura?

**Comment by Lor1co** [comment]
![image](https://user-images.githubusercontent.com/97855952/173601817-eba321b6-b7fb-4cda-b06f-74540147d384.png)
yes meteor's killaura same.

**Comment by Nekiplay** [comment]
Is one of your mods breaking rotation

**Comment by Nekiplay** [comment]
And brandpacket not needed since Meteor Client has a Server spoof

**Comment by Lor1co** [comment]
Ik but it doesnt work with jex client

**Comment by Nekiplay** [comment]
I think it breaks the Jex Client

**Comment by Lor1co** [comment]
yes it works without jex
