### ISSUE TITLE
[Bug] It crashes when i open it

### ISSUE THREAD

**Issue by d4p-1** [Nekiplay/MeteorPlus#80]
### Describe the bug

crashes

### Steps to reproduce

```bash
when you open the meteor minecraft
```

### Meteor Plus Version

latest

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by qingshu-ui** [comment]
Please provide more detailed crash logs, maybe I can see the reason

**Comment by qingshu-ui** [comment]
Hi , You may not have noticed that starting from Meteor Client version 0.5.5, Baritone is not included in Meteor Client. You need to download the Baritone mod jar file separately and place it in your mods folder.

**Comment by Nekiplay** [comment]
Install Baritone API!!!!!!!!!!!!!
