### ISSUE TITLE
[Bug] crashing when set to randomization to 0 in killaura

### ISSUE THREAD

**Issue by uexeduck** [Nekiplay/MeteorPlus#81]
### Describe the bug

self explanatory.

### Steps to reproduce

```bash
in killaura+ setting rotation randomize to "random" and setting the multiply to 0 crashes the game
```

### Meteor Plus Version

1.0.4

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by d4p-1** [comment]
in: "Steps to reproduce
in killaura+ setting rotation randomize to "random" and setting the multiply to 0 crashes the game" i said that it crashes on launch but it set this for me.(i use Tlauncher)

**Comment by d4p-1** [comment]
OH SHIT TOUGHT THIS WAS MY COMMENT LOL

**Comment by qingshu-ui** [comment]
This crash only needs to be resolved by limiting the minimum value of random multipliers.

**Comment by Nekiplay** [comment]
It's a known bug, I don't think I'll fix it.
