### ISSUE TITLE
NCP+/UNCP bypasses

### ISSUE THREAD

**Issue by Renartared** [Nekiplay/MeteorPlus#83]
### Description

Add bypasses for NCP+/UNCP such as bypassing velocity, bypassing no slow, or bypassing nofall

### Before submitting a suggestion

- [X] This feature doesn't already exist.

- [X] This wasn't already suggested.

**Comment by d4p-1** [comment]
kool. Now make them add matrix,watchdog,versus+,polar, grim v1/2 and ACC5(this is a troll, ik that coding is hard don't take this sereously)

**Comment by Renartared** [comment]
He can just port bypasses over from 1.8 clients

**Comment by Nekiplay** [comment]
> Can't because they are forge and it is fabric

In principle, I did that, but it's not easy because of the different APIs

**Comment by Anonimouze** [comment]
> > Can't because they are forge and it is fabric
> 
> In principle, I did that, but it's not easy because of the different APIs

Okay then. Also when will the client update to 1.20.4?

**Comment by Nekiplay** [comment]
> > > Can't because they are forge and it is fabric
> > 
> > 
> > In principle, I did that, but it's not easy because of the different APIs
> 
> Okay then. Also when will the client update to 1.20.4?

[#fc5](https://github.com/Nekiplay/MeteorPlus/commit/fc5908673de18c5f1e179e49d538564ce89cd58f)

**Comment by Anonimouze** [comment]
> > > > Can't because they are forge and it is fabric
> > > 
> > > 
> > > In principle, I did that, but it's not easy because of the different APIs
> > 
> > 
> > Okay then. Also when will the client update to 1.20.4?
> 
> [#fc5](https://github.com/Nekiplay/MeteorPlus/commit/fc5908673de18c5f1e179e49d538564ce89cd58f)

Thanks
