### ISSUE TITLE
[Bug] when i try to launch it crashes launcher is "Hello Minecraft" 

### ISSUE THREAD

**Issue by justchillingrnyk** [Nekiplay/MeteorPlus#86]
### Describe the bug

just search the launcher on google btw 
[minecraft-exported-crash-info-2023-12-18T19-30-53.zip](https://github.com/Nekiplay/MeteorPlus/files/13707287/minecraft-exported-crash-info-2023-12-18T19-30-53.zip)

### Steps to reproduce

```bash
so when i try to run with meteor plus it crashes
```

### Meteor Plus Version

1.0.4

### Minecraft Version

1.20.2 fabric 

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Nekiplay** [comment]
Install Baritone API in your mods folder
