### ISSUE TITLE
(not a bug but a question) How do i set up the chatgpt module

### ISSUE THREAD

**Issue by orangesplash69** [Nekiplay/MeteorPlus#88]
### Describe the bug

How do i set up the **chat gpt** module?

### Steps to reproduce

```bash
no steps cuz no bug
```

### Meteor Plus Version

1.20.1 

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [x] This is a valid bug.
- [x] This bug wasn't already reported.

**Comment by Nekiplay** [comment]
Get token in https://discord.gg/nwy8TQm6
Set mode NagaAI
