### ISSUE TITLE
[Suggestion] Vulcan Nofall and Elytra-less Speed

### ISSUE THREAD

**Issue by Anonimouze** [Nekiplay/MeteorPlus#89]
### Description

The Nofall could be ported from Liquidbounce-nextgen and the speed could be ported from FDPClient if Possible.

### Before submitting a suggestion

- [X] This feature doesn't already exist.

- [X] This wasn't already suggested.

**Comment by Nekiplay** [comment]
AntiCheat Version?

**Comment by Nekiplay** [comment]
Try https://github.com/Nekiplay/MeteorPlus/commit/861ccdb8cbf5064c5d8b0f098284b5074dac1303

**Comment by Nekiplay** [comment]
NoFall Vulcan from FDP It was already in the addon

**Comment by Anonimouze** [comment]
Thank you very much. Now can you please add the Elytra-less speed for Vulcan?

**Comment by Anonimouze** [comment]
Also you can Improve the Nofall by adding a code that checks if the block you are falling too will make you take damage like water, cobwebs, berrybush etc. If any of these blocks are under you It will cancel the nofall since it gives 2 hearts of damage every time it activates. No pressure of course and thanks for the great addon.

**Comment by Anonimouze** [comment]
Also you can improve the old Vulcan nofall by making it activate only when falling from a certan height.

**Comment by Nekiplay** [comment]
> Thank you very much man. Now can you please add the Elytra-less speed for Vulcan?

Speed for Vulcan Already has, this bypass use Elytra in hotbar

**Comment by Anonimouze** [comment]
> > Thank you very much man. Now can you please add the Elytra-less speed for Vulcan?
> 
> Speed for Vulcan Already has, this bypass use Elytra in hotbar

Im talking about speed without elytra because elytra is not accessible in every server

**Comment by Anonimouze** [comment]
> > Thank you very much man. Now can you please add the Elytra-less speed for Vulcan?
> 
> Speed for Vulcan Already has, this bypass use Elytra in hotbar

Also are you russian?
