### ISSUE TITLE
killaura-plus crash

### ISSUE THREAD

**Issue by DeeKahy** [Nekiplay/MeteorPlus#9]
I found a settings combination that crashes the game when a player, fake player or mob comes into the killaura radius.
The crash occurred whilst I was changing the rotate settings.
![image](https://user-images.githubusercontent.com/97156953/177059293-6fae7bbe-f1f7-4fd2-950d-f56b8301cba4.png)

Crash logs:
https://pastebin.com/t8CW1RZq

**Comment by Nekiplay** [comment]
try again in last build

**Comment by Nekiplay** [comment]
fixed
