### ISSUE TITLE
How do I use X-Ray bruteforce and Baritone together?

### ISSUE THREAD

**Issue by Horcag** [Nekiplay/MeteorPlus#90]
### Description

I want it to be possible to use Baritone to mine discovered ores.

### Before submitting a suggestion

- [X] This feature doesn't already exist.

- [X] This wasn't already suggested.

**Comment by Nekiplay** [comment]
> ### Description
> I want it to be possible to use Baritone to mine discovered ores.
> 
> ### Before submitting a suggestion
> * [x]  This feature doesn't already exist.
> * [x]  This wasn't already suggested.

X-Ray bruteforce Not intended as a baritone prey.

**Comment by Horcag** [comment]
> > ### Description
> > I want it to be possible to use Baritone to mine discovered ores.
> > ### Before submitting a suggestion
> > 
> > * [x]   This feature doesn't already exist.
> > * [x]   This wasn't already suggested.
> 
> X-Ray bruteforce Not intended as a baritone prey.

Is there any possibility of merging them in the future?

**Comment by Nekiplay** [comment]
> Is there any possibility of merging them in the future?

Hardly
