### ISSUE TITLE
[Suggestion] Add custom endpoint option to ChatGPT

### ISSUE THREAD

**Issue by HAV0X1014** [Nekiplay/MeteorPlus#94]
### Description

There are now many services that offer an OpenAI-style endpoint, and many of these don't require a key to use. For example, I host a llama.cpp server without any authentication to use. I would like to see any endpoint be usable. In theory there wouldn't need to be any large changes to the code.

An example of a custom endpoint is `https://123.45.6.78:8192/v1/chat/completions`. (please allow the user to specify the *whole* URL to be used, as not every service has the same URL style)

### Before submitting a suggestion

- [X] This feature doesn't already exist.

- [X] This wasn't already suggested.

**Comment by Nekiplay** [comment]
Wait for it
