### ISSUE TITLE
Crash 1.20.4

### ISSUE THREAD

**Issue by SevaLeonov** [Nekiplay/MeteorPlus#96]
### Describe the bug

[tl console.log](https://github.com/Nekiplay/MeteorPlus/files/14001011/tl.console.log)

### Steps to reproduce

```bash
Launch Minecraft
```

### Meteor Plus Version

1.0.5

### Minecraft Version

fabric-loader-0.15.6-1.20.4

### Operating System

Windows

### Before submitting a bug report

- [ ] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by SevaLeonov** [comment]
https://pastebin.com/MT9q5ja6

**Comment by Nekiplay** [comment]
Install Baritone
