### ISSUE TITLE
[Bug] Crash 1.20.4

### ISSUE THREAD

**Issue by SevaLeonov** [Nekiplay/MeteorPlus#97]
### Describe the bug

Crash when start game

![image](https://github.com/Nekiplay/MeteorPlus/assets/88166176/c3e29a81-28cf-4a67-a49e-bf531a0051a5)
[crash-2024-01-30_22.08.11-client.txt](https://github.com/Nekiplay/MeteorPlus/files/14103684/crash-2024-01-30_22.08.11-client.txt)

### Steps to reproduce

```bash
start game
```

### Meteor Plus Version

1.0.5

### Minecraft Version

fabric-loader-0.15.6-1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Nekiplay** [comment]
Delete "baritone-1.20.4" meteor-plus need only "baritone-api-fabric-1.20.4"

**Comment by SevaLeonov** [comment]
> Delete "baritone-1.20.4" meteor-plus need only "baritone-api-fabric-1.20.4"

 I did this, but the game crash again

[crash-2024-01-31_10.18.24-client.txt](https://github.com/Nekiplay/MeteorPlus/files/14109060/crash-2024-01-31_10.18.24-client.txt)

**Comment by SevaLeonov** [comment]
If I don`t use meteorplus and use only meteor everything good. Crash only with meteorplus

**Comment by SevaLeonov** [comment]
And if I use older version meteor+meteorplus everything good

**Comment by SevaLeonov** [comment]
And can i get meteorplus 1.20.4 without Baritone?

**Comment by Nekiplay** [comment]
Meteor Plus has not been working for a long time and it is with the addition of support for minimaps and Freecam

**Comment by Nekiplay** [comment]
Try Baritone from Guilded

**Comment by Nekiplay** [comment]
> And if I use older version meteor+meteorplus everything good

Perhaps the problem is in the new version of the meteor client, download the stable version of the client and Meteor Plus from Guilded, which works for sure
Later I will check the new versions of the Meteor Client and fix the crashes

**Comment by Nekiplay** [comment]
Guilded link: https://www.guilded.gg/i/27dAlJKk

**Comment by Nekiplay** [comment]
Specify the version of the Meteor Client

**Comment by SevaLeonov** [comment]
> Specify the version of the Meteor Client

0.5.6-2002

**Comment by Nekiplay** [comment]
In Releases now contains work meteor client version
