### ISSUE TITLE
[Suggestion] PVP Addons

### ISSUE THREAD

**Issue by tfoskeehc** [Nekiplay/MeteorPlus#98]
### Description

sprint reset (w tap/s tap), jump reset (reduce kb by jumping right before attack), and p-crits (hits once moving upwards from getting hit)

### Before submitting a suggestion

- [X] This feature doesn't already exist.

- [X] This wasn't already suggested.

**Comment by Nekiplay** [comment]
Meteor Plus basically a PVE addon
